// <auto-generated />
namespace Repo.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterrelationv5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterrelationv5));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141905474_alter-relation-v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
