// <auto-generated />
namespace Repo.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class employeestatusrelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeestatusrelations));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141831442_employee-status-relations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
